### ISSUE TITLE
Do you need to crop the face from the trainset and testset?

### ISSUE THREAD

**Issue by FelixZhang7** [feascr/3d-mask-pad-iccv2021#1]

**Comment by feascr** [comment]
No, I used raw data from train and test sets. You can find more about preprocessing [here](https://github.com/feascr/3d-mask-pad-iccv2021/blob/e8f624f788f0af7bc75b22065164d6178e159a57/preprocessors/competition_preprocessor.py).

**Comment by FelixZhang7** [comment]
cut out the face may get a better ranking?

**Comment by feascr** [comment]
Unfortunately, I did not test this approach.
